# sources.mk - what native.mk and guest.mk both build: the same files with the
# same defines, so the native reference and the sandboxed core are the same
# program. Included, not run.

ROOT := ..
RAWGL := $(ROOT)/extern/rawgl
MINIZ := $(ROOT)/extern/miniz
ZLIB  := $(ROOT)/extern/zlib
STB   := $(ROOT)/extern/stb
TSF   := $(ROOT)/extern/TinySoundFont
MUNT  := $(ROOT)/extern/munt/mt32emu/src
MB    ?= $(or $(MINIBOX_DIR),$(HOME)/chimera/extern/chimera-common-minibox)

# ---- rawgl, upstream: its Makefile's SRCS less its frontend - main.cpp,
# systemstub_sdl.cpp and graphics_gl.cpp (the SDL window and the OpenGL
# renderer); the core is the frontend instead. mixer.cpp is compiled as it is,
# against the core's SDL_mixer device (compat/, sdl-shim.cpp).
#
# Upstream's Makefile defines BYPASS_PROTECTION; the core does not: the game
# starts where the original starts, at the copy protection's symbols (DOS with
# a password screen, Amiga, Atari ST), as rawgl's own code has it without the
# define. RAWGL_MEMFS is the core's (patches/0001): files come from memory.
RAWGL_NAMES := aifcplayer bitmap file engine graphics_soft script mixer pak resource resource_nth \
	resource_win31 resource_3do scaler screenshot sfxplayer staticres unpack util video
RAWGL_SRCS := $(addprefix $(RAWGL)/,$(addsuffix .cpp,$(RAWGL_NAMES)))
# as upstream's Makefile, less -g, SDL and its defines: -O2 for a release.
# Its assertions stay on, in both builds (-UNDEBUG undoes the guest flags'
# -DNDEBUG): upstream's checks on the data are part of the program, and a
# failed one halts the machine with its message (halt.c) where upstream's
# process would abort.
RAWGL_CXXFLAGS_COMMON := -std=gnu++11 -O2 -UNDEBUG -DRAWGL_MEMFS -Icompat -I$(RAWGL) -I$(ZLIB) -I$(ROOT)/build/munt-config -I$(MUNT)

# ---- miniz (the submodule extern/miniz, tag 3.0.2): the zip reader the
# project's game files come through. Its zlib-compatible names are off:
# zlib itself is below.
MINIZ_NAMES := miniz miniz_tdef miniz_tinfl miniz_zip
MINIZ_SRCS := $(addprefix $(MINIZ)/,$(addsuffix .c,$(MINIZ_NAMES)))
# miniz runs at Init, off the engine's stack: its assertions are off in both
# builds (the guest flags' -DNDEBUG, and here the native build's)
MINIZ_DEFS := -DMINIZ_NO_STDIO -DMINIZ_NO_TIME -DMINIZ_NO_ZLIB_COMPATIBLE_NAMES
MINIZ_CFLAGS_COMMON := -std=gnu11 -O2 -DNDEBUG -Icompat -I$(MINIZ) $(MINIZ_DEFS)

# ---- zlib (the submodule extern/zlib, tag v1.3.1): the gzip inflate the 20th
# Anniversary Edition's pictures and sounds (.bgz, .wgz) are read with
# (resource_nth.cpp inflateGzip) - its inflate half only
ZLIB_NAMES := adler32 crc32 inffast inflate inftrees zutil
ZLIB_SRCS := $(addprefix $(ZLIB)/,$(addsuffix .c,$(ZLIB_NAMES)))
ZLIB_CFLAGS_COMMON := -std=gnu11 -O2 -DNDEBUG -I$(ZLIB)

# ---- Munt's libmt32emu (the submodule extern/munt, at the commit the SDLPoP2
# core builds, libmt32emu 2.8.3): the Roland CM-32L the DOS release's sound
# effects can play on (rawgl's --mt32, the mt32 setting). The library its CMake
# build makes (mt32emu/CMakeLists.txt libmt32emu_CPP_SOURCES), less the
# resamplers that need libsoxr or libsamplerate and the version tagging of a
# shared object. C++; Munt's own flags are its CMake defaults.
MUNT_NAMES := Analog BReverbModel Display File FileStream LA32FloatWaveGenerator LA32Ramp LA32WaveGenerator \
	MidiStreamParser Part Partial PartialManager Poly ROMInfo Synth Tables TVA TVF TVP sha1/sha1 SampleRateConverter \
	c_interface/c_interface srchelper/srctools/src/FIRResampler srchelper/srctools/src/SincResampler \
	srchelper/srctools/src/IIR2xResampler srchelper/srctools/src/LinearResampler srchelper/srctools/src/ResamplerModel \
	srchelper/InternalResampler
MUNT_SRCS := $(addprefix $(MUNT)/,$(addsuffix .cpp,$(MUNT_NAMES)))
# its config.h, generated by CMake upstream: the core's own (munt-config.h)
MUNT_CONFIG := $(ROOT)/build/munt-config/config.h
$(MUNT_CONFIG): munt-config.h
	@mkdir -p $(dir $@)
	cp munt-config.h $@
MUNT_CXXFLAGS_COMMON := -std=c++11 -O2 -I$(ROOT)/build/munt-config -I$(MUNT)

# ---- stb_vorbis (extern/stb) and TinySoundFont (extern/TinySoundFont): the
# 20th Anniversary Edition's Ogg Vorbis music and Windows 3.1's MIDI music,
# compiled in the core's own translation units (vorbis.c, midi.c) over its
# deterministic math (detmath.h)

# ---- the core
CORE_C_NAMES := coro files halt midi vorbis wbx-entry
CORE_CXX_NAMES := rawgl-driver sdl-shim
CORE_HDRS := rawgl-driver.h rawgl-files.h rawgl-audio.h coro.h midi.h detmath.h $(MUNT_CONFIG) $(wildcard compat/*.h) $(wildcard $(RAWGL)/*.h)
CORE_CFLAGS_COMMON := -std=gnu11 -O2 -Icompat -I$(MINIZ) $(MINIZ_DEFS) -I$(STB) -I$(TSF)
CORE_CXXFLAGS_COMMON := $(RAWGL_CXXFLAGS_COMMON) -I$(STB)

# the calls the core answers itself (rawgl-driver.cpp): the engine's clock at
# start (the random seed) is the project's setting, and rand() is the same
# generator in both builds
WRAP_FLAGS := -Wl,--wrap=time -Wl,--wrap=rand -Wl,--wrap=srand

# the patch series goes onto the submodule before anything of rawgl builds
PATCH_STAMP := $(ROOT)/build/patches.stamp
$(PATCH_STAMP): $(wildcard $(ROOT)/patches/*.patch) apply-patches.sh
	sh apply-patches.sh
	@mkdir -p $(dir $@)
	@touch $@

# Every object depends on the flags it was built with: a change to them
# rebuilds it.
define flags_stamp
$(shell mkdir -p $(1); printf '%s\n' '$(2)' | cmp -s - $(1)/flags || printf '%s\n' '$(2)' > $(1)/flags)
endef
